// <auto-generated />
using La_mia_pizzeria.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace La_mia_pizzeria.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20240515124816_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("La_mia_pizzeria.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pizza_description");

                    b.Property<string>("_img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pizza_img");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pizza_name");

                    b.Property<decimal>("_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pizza_price");

                    b.HasKey("Id");

                    b.ToTable("pizza");
                });
#pragma warning restore 612, 618
        }
    }
}
